version: '3'
services:
  postgresdb:
    image: postgres
    container_name: postgresdb
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 7410
      POSTGRES_DB: invoice
    ports:
      - 5433:5432
    volumes:
      - db:/var/lib/postgres
 
  app:
    container_name: app
    depends_on:
      postgresdb:
        condition: service_healthy
    build: .
    restart: unless-stopped
    environment:
      DB_PORT: 5432  # Set the port of the database service
      DB_USER: postgres  # Set the database username
      DB_PASSWORD: 7410  # Set the database password
      DB_NAME: invoice  # Set the database name
      DATABASE_URL: 'postgresql://postgres:7410@postgresdb:5432/invoice?schema=public'
    ports: 
      - 3001:3001
      - 3000:3000
    stdin_open: true
    tty: true

volumes:
  db:
